# Generated by Django 3.0.8 on 2020-08-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricesource', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pricetaker',
            new_name='Pricesource',
        ),
    ]
