# Generated by Django 3.0.7 on 2020-07-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatesPredictionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Currency')),
            ],
        ),
    ]
