# Generated by Django 3.0.8 on 2020-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertpreference',
            old_name='alert_down',
            new_name='days_forecast',
        ),
        migrations.RenameField(
            model_name='alertpreference',
            old_name='alert_down_forecast',
            new_name='percentage_down',
        ),
        migrations.AddField(
            model_name='alertpreference',
            name='percentage_down_forecast',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
