# Generated by Django 3.0.8 on 2020-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200825_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertpreference',
            name='days_forecast',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='percentage_down',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='percentage_down_forecast',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
    ]
