# Generated by Django 3.0.8 on 2020-08-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricetaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('data_source', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
