# Generated by Django 3.0.8 on 2020-08-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricetaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetaker',
            name='data_source',
            field=models.CharField(default='', max_length=500),
        ),
    ]
