# Generated by Django 3.0.8 on 2020-08-19 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricetaker', '0002_auto_20200804_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetaker',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricetaker',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
