# Generated by Django 3.0.8 on 2020-09-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateshistory',
            name='date',
            field=models.DateField(),
        ),
    ]
