# Generated by Django 3.0.8 on 2020-08-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='logo_path',
            field=models.CharField(default='', max_length=50),
        ),
    ]
