# Generated by Django 3.0.7 on 2020-07-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateshistory',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
