# Generated by Django 3.0.7 on 2020-06-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='short_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
