# Generated by Django 3.0.8 on 2020-08-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_bank_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo_path',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
