# Generated by Django 3.0.8 on 2020-09-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200901_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateshistory',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
