# Generated by Django 3.0.8 on 2020-08-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomContentType',
        ),
    ]
